import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navabar";
import Footer from "../components/ui/footer/Footer";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-900`}
      >
        <div
          className="
            relative
            bg-white
            rounded-t-[40px]
            shadow-sm
            overflow-hidden
            flex flex-col
          "
        >
          <div
            className="absolute top-[-150px] left-1/2 -translate-x-1/2"
            style={{
              width: "766.724px",
              height: "500.15px",
              borderRadius: "766.724px",
              opacity: 0.2,
              background: "rgba(201, 253, 116, 0.32)",
              filter: "blur(100px)",
              zIndex: 0,
            }}
          />

          <Navbar />
          <Toaster position="top-right" reverseOrder={false} />
          <main className="flex-1 w-full max-h-full  relative z-10 overflow-hidden">
            <Providers>{children}</Providers>
          </main>

          <footer className="mt-auto relative z-10">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
